name: Build project and Run Lighthouse CI
on: [push]

jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 10.x with Corepack
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
          cache: 'npm'

      - name: Enable Corepack
        run: npx corepack enable

      - name: Install dependencies and build
        run: |
          npx corepack yarn install
          npm run build

      - name: Install Lighthouse CI
        run: npx corepack npm install -g @lhci/cli@0.3.x

      - name: Run Lighthouse CI
        run: npx corepack lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed"
